services:
  vaultwarden:
    volumes:
      - letsencrypt-certs:/certs
    environment:
      DOMAIN: ${DOMAIN}
      VIRTUAL_PORT: ${VIRTUAL_PORT:-80}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PROTO: ${VIRTUAL_PROTO:-https}
      ROCKET_TLS: '{certs="/certs/${VIRTUAL_HOST}/fullchain.pem",key="/certs/${VIRTUAL_HOST}/key.pem"}'
    networks:
      - letsencrypt-network

volumes:
  letsencrypt-certs:
    external: true

networks:
  letsencrypt-network:
    name: letsencrypt-network
    external: true